[general]
name = "docpage-generator"
version = "0.2.0"
fix_version = "1.5.0"
authors = ["tttmmmyyyy"]
license = "MIT"

[build]
files = ["main.fix", "semver.fix", "records.fix", "store.fix", "generate.fix", "site.fix"]

[[dependencies]]
name = "json"
version = "0.5.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-json.git" }

[[dependencies]]
name = "ez-scripting"
version = "0.4.0"
git = { url = "https://github.com/tttmmmyyyy/ez_scripting.git" }
